---
# Grafana role metadata
galaxy_info:
  author: DOITPAY Team
  description: Role to install and configure Grafana
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - monitoring
    - grafana
    - dashboard
    - visualization

dependencies: []
