groups:
  - name: devops_learning_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 2 minutes"

      - alert: HighMemoryUsage
        expr: 100 * (1 - ((node_memory_MemAvailable_bytes{}) / (node_memory_MemTotal_bytes{}))) > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 2 minutes"

      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 30 seconds"

      - alert: HighAPIErrorRate
        expr: rate(api_http_request_duration_seconds_count{status_code=~"5.."}[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High API error rate"
          description: "API error rate is above 10% for more than 1 minute"

      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(api_http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow API response time"
          description: "95th percentile API response time is above 2 seconds"

      - alert: MySQLConnectionsHigh
        expr: mysql_global_status_threads_connected > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High MySQL connections"
          description: "MySQL has more than 50 active connections"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes > 1073741824  # 1GB
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 1GB"

      - alert: ContainerCPUHigh
        expr: rate(container_cpu_usage_seconds_total{name=~".+"}[5m]) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High container CPU usage"
          description: "Container {{ $labels.name }} CPU usage is above 80%"

      - alert: ContainerMemoryHigh
        expr: container_memory_usage_bytes{name=~".+"} > 536870912  # 512MB
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High container memory usage"
          description: "Container {{ $labels.name }} memory usage is above 512MB"

      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 20
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 20% on root filesystem"
