global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'express-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['devops_express_api:3001']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['devops_mysql_exporter:9104']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3001']

  # OpenSearch monitoring via dummy endpoint for status check
  # - job_name: 'opensearch'
  #   static_configs:
  #     - targets: ['opensearch:9200']
  #   metrics_path: '/'
  #   scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['testing-web-client:80']
    metrics_path: '/nginx_status'

  - job_name: 'superset'
    static_configs:
      - targets: ['superset:8088']
    metrics_path: '/health'
