apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  
  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: "[logs-*]"
    jsonData:
      esVersion: 7.10.0
      timeField: "@timestamp"
    editable: true
