---
# Vue-app role metadata
galaxy_info:
  author: DOITPAY Team
  description: Role to deploy Vue.js application with Nginx
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - web
    - vue
    - nodejs
    - nginx
    - frontend

dependencies: []
